# Generated by Django 2.0.5 on 2018-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_luadciseqtl_cancer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('synonyms', models.TextField(blank=True, db_column='Synonyms', null=True)),
                ('targets', models.TextField(blank=True, db_column='Targets', null=True)),
                ('target_pathway', models.TextField(blank=True, db_column='Target pathway', null=True)),
            ],
            options={
                'db_table': 'drug_list',
                'managed': True,
            },
        ),
        migrations.AlterModelTable(
            name='luadciseqtl',
            table='cis_eqtl',
        ),
    ]
